const express = require('express');
const router = express.Router();

router.use("/", (request, response, next) => {

    let respuesta = '<!DOCTYPE html>';
    respuesta += '<head>';
    respuesta += '<title> A01276775_Lab10 </title>';
    respuesta += '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">';
    respuesta += '<link rel="stylesheet" href="css/style.css" media="screen,projection"/>';
    respuesta += '<meta charset="utf-8" />';
    respuesta += '</head>';
    respuesta += '<body>';
    respuesta += '<nav class="navbar is-black" role="navigation" aria-label="main navigation">';
    respuesta += '<div class="navbar-brand">  ';         
    respuesta += '<a class="navbar-item " href="https://bulma.io">';
    respuesta += '<img src="https://images.vexels.com/media/users/3/144097/isolated/preview/3dedcd235214cdde6b4e171fdbf66c9d-icono-de-corazon.png"';
    respuesta += 'alt="Just a hearth" width="40" height="28">';
    respuesta += '</a> ';          
    respuesta += '<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">';
    respuesta += '<span aria-hidden="true"></span>';
    respuesta += '<span aria-hidden="true"></span>';
    respuesta += '<span aria-hidden="true"></span>';
    respuesta += '</a>';
    respuesta += '</div>';
    respuesta += '</nav>';
    respuesta += '<header>';      
    respuesta += '<div id=Content>';
    respuesta += '<img id="logo" src="https://i.pinimg.com/564x/c6/80/7a/c6807aeee472af3d95ea0e2c9821f1d1.jpg" alt="Imagen Anya"><br>';
    respuesta += '<br>';           
    respuesta += '<H2> <center> Laboratorio 10 </center>  <br>';
    respuesta += '<center>  Rutas y formas </center> <br>';
    respuesta += '</H2>';
    respuesta += '</header>';
    respuesta += '<hr>';
    respuesta += '<div id="Datos">';
    respuesta += 'Nombre: Monserrat Karime Moreno Casas <br>';
    respuesta += 'Edad: 20 años <br>';
    respuesta += 'Matricula : A01276775 <br>';
    respuesta += 'Correo electrónico: A01276775@tec.mx<br>';
    respuesta += '</div>';      
    respuesta += '<hr>';
    respuesta += '<div id="Sobre mi">';
    respuesta += '<div class="box">';
    respuesta += '<article class="media">';
    respuesta += '<div class="media-left">';
    respuesta += '<figure class="image is-96x96">';
    respuesta += '<img src="imagenes/haku1.jpeg" alt="Image">';
    respuesta += '</figure>';
    respuesta += '</div>';
    respuesta += '<div class="media-content">';
    respuesta += '<div class="content">';
    respuesta += '<p><br><br><br>     ';                     
    respuesta += 'El es <strong>Haku</strong>! Un animalito muy cariñoso tiene cuatro meses, le gusta mucho el pollo y las croquetas. ';
    respuesta += 'Prefiere dormir en el piso que en su cama, le gusta mucho correr y meterse en las cajas. ';
    respuesta += '<br><br><br><br>';
    respuesta += '</p>';
    respuesta += '</div>';
    respuesta += '</div>';
    respuesta += '</article>';
    respuesta += '</div>';
    respuesta += '</div><br><br><hr>';
    respuesta += '<center> ';
    respuesta += '<img src="imagenes/Haku2.jpeg" width="200" height="200">';
    respuesta += '<img src="imagenes/Haku3.jpeg" width="200" height="200">';
    respuesta += '<img src="imagenes/Haku5.jpeg" width="150" height="200">';
    respuesta += '<img src="imagenes/Haku4.jpeg" width="150" height="200">';
    respuesta += '</center>';
    respuesta += '<center> ';
    respuesta += '<a href="/Principal"> <button class="button is-danger is-light"> Volver al inicio</button></a> ';
    respuesta += '</center> <br><hr><br> ';
    respuesta += '<footer> Editor de html: Visual Studio Code <a href="https://code.visualstudio.com/"> Link </a> <br>';
    respuesta += '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png"';
    respuesta += 'width="30"';
    respuesta += 'height="40">';
    respuesta += '</footer>';
    respuesta += '</div>';
    respuesta += '</body>';
    respuesta += '</html>';
    

    response.send(respuesta);
});

module.exports = router;